### ISSUE TITLE
db fails to open

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#13]
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.<anonymous> (http://localhost:8080/_snowpack/pkg/idb.with-async-ittr.v7.0.0.js:150:26)
    at DB.names (http://localhost:8080/db.js:69:22)
    at async DB.uniqueName (http://localhost:8080/db.js:108:22)
    at async DB.readDesign (http://localhost:8080/db.js:179:12)

**Comment by gbishop** [comment]
I'm thinking this happens after I clear the data in dev-tools (to reset) with the tab open. I need refresh after clearing because the tab still has the db open.
